apiVersion: v1
kind: Service
metadata:
    name: myapp-service

spec:
   type: NodePort
   ports:
   - targetport: 80   #Running port inside the container
     port: 80         #Service port to connect to targetPort
     nodePort: 40001  #Random port running on kubernetes Host/node
   selector:
     name: myapp
     tier: front-end
    
    
