apiVersion: v1
kind: Secret
metadate:
   name: app-secret
data:
  DB_HOST: mysql
  DB_USER: root
  DB_PASSWORD: passwd
  
  # Above defination all data is in simple text format, which will raise furrther security concerns,Need to convegrt it ot base64 as below
  # echo -n 'mysql' |base64
  # echo -n 'root' |base64
  # echo -n 'passwd' |base64
  ## To decode encrypted valused we can use below commands
  # echo -n 'sfsdgdng' |base64 --decode
