apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: my-claim

spec:
   accessMode:
      - ReadWriteOnce
   storageClassName: google-storage
   resources:
      requests: 
        storage: 500Mi
      
