apiVersion: v1
kind: ReplicationController
metadata:
   name: myapp-rc
   labels:
     app: my-app
     tier: front-end
spec:
 - template:
       metadata:
          name: nginx
          labels:
             name: nginx
             tier: front-end
       spec:
          containers:
          - name: nginx
            image: nginx
 replicas: 3          
   

     
